#!/bin/bash
#
#  schema-hddm: create a hddm template based on a xml schema
#
#  Both templates and schemas are themselves well-formed xml documents,
#  so the transformation can be done automatically using XSLT tools.
#  This implementation uses Xalan from xml.apache.org to carry out the
#  transformation.  Some result is passed through the XercesDOMParser
#  just to check for well-formed xml and improve the readability of the
#  of the template.
#
#  author: richard.t.jones at uconn.edu
#  version: original in perl, September 15, 2003
#
#  version 1.1, February 12, 2021
#  - xerces-perl is no longer supported, convert to bash script
#

function usage() {
   cat << eoi

Usage: schema-hddm  myfile.xsd

reads the schema contained in myfile.xsd and writes to stdout a hddm
template, which is just a xml file that shows the data structure.

eoi
}

if [ $# != 1 ]; then
   usage
   exit 1
fi

infile=$1
if [ ! -r "$infile" ]; then
   echo "schema-hddm error - Unable to open input file $infile"
   exit 1
fi

base=$(basename $infile)
tmpxml=".tmp-$base.xml"

schema_hddm_xslt=$(dirname $0)/../schemas/schema-hddm.xsl

# generate the basic schema using XSL transform:
#
#  two translators: xalan-j (java) or xalan-c (c++)
#  chose one of the two following, comment the other
#$cmd = "$ENV{XALANCROOT}/bin/Xalan -o $tmpxml $infile schema-hddm.xsl";
xalanj2_classpath=/usr/share/java/xalan-j2.jar:/usr/share/java/xalan-j2-serializer.jar
java -cp $xalanj2_classpath org.apache.xalan.xslt.Process \
       -IN $infile -OUT $tmpxml -XSL $schema_hddm_xslt

if [ $? != 0 ]; then
   echo "hddm-schema: errors returned by Xalan, giving up"
   exit 9
fi

# check the result for correctness and pretty-print it
hddm_schema_xsd=$(dirname $0)/../schemas/XMLSchema.xsd
xmllint --format $tmpxml 2> /dev/null

if [ $? != 0 ]; then
   if [ ! -x `which xmllint` ]; then
      echo "Please check that xmllint exists in your path and try again"
      exit 7
   else
      echo "schema-hddm: errors returned by xmllint, giving up"
      exit 6
   fi
fi

rm $tmpxml
exit 0
